[dependencies]
  curl = '*'
  yq = '*'

  [dependencies.ecoscope-workflows-core]
    channel = 'https://repo.prefix.dev/ecoscope-workflows/'
    version = '0.7.3'

  [dependencies.ecoscope-workflows-ext-ecoscope]
    channel = 'https://repo.prefix.dev/ecoscope-workflows/'
    version = '0.7.3'

[project]
  channels = ['https://repo.prefix.dev/ecoscope-workflows/', 'conda-forge']
  name = 'patrols'
  platforms = ['linux-64', 'osx-arm64']

[tasks]
  [tasks.compile]
    cmd = './dev/recompile.sh --install'

  [tasks.curl-invoke]
    cmd = './dev/curl-invoke-docker.sh'

  [tasks.docker-build]
    cmd = './dev/docker-build.sh patrols'

  [tasks.docker-run]
    cmd = './dev/docker-run.sh patrols'

  [tasks.pytest-app]
    cmd = "./dev/pytest.sh patrols 'app'"

  [tasks.pytest-cli]
    cmd = "./dev/pytest.sh patrols 'cli'"

  [tasks.recompile]
    cmd = './dev/recompile.sh --update'
